name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Use Node.js 14
      uses: actions/setup-node@v3
      with:
        node-version: 14.10.1

    - name: install
      run: npm install

    - name: build
      run: npm run build

    - name: build - 404.html
      run: cp dist/index.html dist/404.html

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: 'master.vtbs.moe'
        force_orphan: true
        user_name: 'nanashi'
        user_email: 'example@example.com'
